// https://vitest.dev/guide/#configuring-vitest

import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { shadowStyle } from "vite-plugin-shadow-style";

// https://vitejs.dev/config/
export default defineConfig(({ mode }) => ({
  css: {
    modules: {
      // https://vitejs.dev/config/shared-options.html#css-modules
      // https://github.com/madyankin/postcss-modules?tab=readme-ov-file#generating-scoped-names
      generateScopedName: "[name]__[local]___[hash:base64:5]",
    },
  },
  build: {
    sourcemap: mode === "development",
    rollupOptions: {
      plugins: [shadowStyle()],
      input: "src/web-component.tsx",
      output: {
        // The vite-plugin-shadow-style uses the css file generated by rollup,
        // so we cannot use format iife because we need the css content in its own file.
        // format: "iife",
        entryFileNames: "index.js",
      },
    },
  },
  plugins: [react()],
  resolve: {
    alias: { src: "/src" },
  },
}));
